
volumes:
  mlflow-cyberbullying-artifact-store:
  postgresql-mlflow-data:

x-app-template: &APP_TEMPLATE
  user: "${USER_ID:-1000}"
  hostname: "${HOST_NAME:-jihoahn}"
  image: cyberbullying-model
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    args:
      USER_NAME: "${USER_NAME:-jihoahn}"
      USER_ID: "${USER_ID:-1000}"
  env_file:
    - .envs/postgres.env
    - .envs/mlflow-common.env
    - .envs/mlflow-dev.env
  volumes:
    - ./:/app/
    - ~/.config/gcloud/:/home/${USER_NAME:-jihoahn}/.config/gcloud
    - mlflow-cyberbullying-artifact-store:/mlflow-cyberbullying-artifact-store
  ipc: host
  init: true


services:
  mlflow-db:
    container_name: mlflow-backend-store
    image: postgres:14
    env_file:
      - .envs/mlflow-common.env
      - .envs/mlflow-dev.env
      - .envs/postgres.env
    volumes: 
      - postgresql-mlflow-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "backend", "-d", "backend"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev
    
  app-dev: 
    <<: *APP_TEMPLATE
    container_name: cyberbullying-model-dev-container
    ports:
      - 8080:8080
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    depends_on:
      mlflow-db:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - dev

  app-prod:
    <<: *APP_TEMPLATE
    container_name: cyberbullying-model-prod-container
    env_file:
      - .envs/mlflow-common.env
      - .envs/mlflow-prod.env
      - .envs/infrastructure.env
    ports:
      - ${PROD_MLFLOW_SERVER_PORT}:${PROD_MLFLOW_SERVER_PORT}
    profiles:
      - prod
  
  app-ci:
    <<: *APP_TEMPLATE
    container_name: cyberbullying-model-ci-container
    ports:
      - ${LOCAL_DEV_MLFLOW_SERVER_PORT}:${LOCAL_DEV_MLFLOW_SERVER_PORT}
    profiles:
      - ci


